services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  demo-jdriven:
    image: demo-jdriven:0.0.1-SNAPSHOT
    depends_on:
      wiremock:
        condition: service_healthy
    environment:
      - client.root.uri=http://wiremock:8080
  
  wiremock:
    image: "wiremock/wiremock:latest"
    volumes:
      - ./src/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]