services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'

  demo-jdriven:
    image: demo-jdriven:0.0.1-SNAPSHOT
    ports:
      - "18080:8080"
    depends_on:
      wiremock:
        condition: service_healthy
      postgres:
        condition: service_started
    environment:
      - client.root.uri=http://wiremock:8080
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.url=jdbc:postgresql://postgres:5432/mydatabase
      - spring.datasource.username=myuser
      - spring.datasource.password=secret
      - spring.datasource.driver-class-name=org.postgresql.Driver

  wiremock:
    image: "wiremock/wiremock:latest"
    volumes:
      - ./src/wiremock/__files:/home/wiremock/__files
      - ./src/wiremock/mappings:/home/wiremock/mappings
    entrypoint: [ "/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose" ]